name: Build project using muddy and upload artifact and inject Mupdate

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Download Updater.lua
        run: |
          mkdir -p src/scripts
          curl -L -o src/scripts/Updater.lua https://github.com/gesslar/mupdate/releases/latest/download/Updater.lua

      - name: Check and create scripts.json if it doesn't exist
        run: |
          if [ ! -f src/scripts/scripts.json ]; then
            mkdir -p src/scripts
            echo '[]' > src/scripts/scripts.json
          fi

      - name: Update scripts.json
        run: |
          jq '. += [{"isActive": "yes", "isFolder": "no", "name": "Updater", "script": ""}]' src/scripts/scripts.json > tmp.json && mv tmp.json src/scripts/scripts.json

      - name: Read mfile variables
        id: mfile_vars
        run: |
          package=$(jq -r '.package' mfile)
          version=$(jq -r '.version' mfile)
          echo "package=$package" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: "create version file"
        id: create_version_file
        run: |
          filename="${{ steps.mfile_vars.outputs.package }}_version.txt"
          echo "filename=$filename" >> $GITHUB_OUTPUT
          echo "${{ steps.mfile_vars.outputs.version }}" > "$filename"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Build with muddy
        run: npx --yes @gesslar/muddy

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/${{ steps.mfile_vars.outputs.package }}.mpackage,${{ steps.create_version_file.outputs.filename }}"
          allowUpdates: true
          bodyFile: "./README.md"
          generateReleaseNotes: true
          tag: ${{ steps.mfile_vars.outputs.version }}
